#!/bin/bash

[ -f /boot/boatinstrument.json ] && mv /boot/boatinstrument.json /
[ -f /boot/boatinstrument.config ] && mv /boot/boatinstrument.config /etc/boatinstrument-fpi/config

. /etc/boatinstrument-fpi/config

export BOAT_INSTRUMENT_ARGS

/usr/bin/flutter-pi $FLUTTER_PI_ARGS /usr/share/boatinstrument-fpi

cp /boatinstrument.json /boot/boatinstrument.json.running
