#!/bin/bash

[ -f /boot/boatinstrument.json ] && mv /boot/boatinstrument.json /

export BOAT_INSTRUMENT_ARGS="--no-audio --no-brightness-ctrl --no-keep-awake"

/usr/bin/flutter-pi --release /usr/share/boatinstrument-fpi

