#!/bin/bash

name=boatinstrument

version=$(awk -F '[ :+]*' '/^version:/ {print $2}' pubspec.yaml)

arch=$(dpkg --print-architecture)

[ ${arch} == 'amd64' ] && { pi_opts="--arch=x64"; }
[ ${arch} == 'arm64' ] && { pi_opts="--arch=arm64"; }

date=$(date +"%a, %d %b %Y %T %z")
. /etc/os-release

prepackage () (
  rm -rf debian
  mkdir -p debian/DEBIAN debian/usr/share/doc/${name}
)

package () (
  post=$1; shift
  deps=$@

  m4 -D__NAME__=${name} -D__VERSION__=$version -D__DATE__="$date" changelog.m4 > debian/usr/share/doc/${name}/changelog

  cp debian/usr/share/doc/${name}/changelog debian/usr/share/doc/${name}/changelog.Debian
  cp copyright debian/usr/share/doc/${name}

  gzip --force --best debian/usr/share/doc/${name}/changelog*

  size=$(du -s debian | awk '{print $1}')

  m4 -D__NAME__=${name} -D__VERSION__=$version -D__RELEASE__=$VERSION_ID -D__ARCH__=${arch} -D__DEPS__="${deps}" -D__POST__=${post} -D__SIZE__=${size} debian-control.m4 > debian/DEBIAN/control

  fakeroot dpkg-deb --build debian packages
)

mkdir -p packages

# ================================ Linux ====================================
flutter build linux
prepackage
cpu=$(uname -m)
mkdir -p debian/usr/share/applications
mv build/linux/${cpu:0:1}*/release/bundle debian/usr/share/${name}
cp name.phil.seeley.boatinstrument.desktop debian/usr/share/applications
package "" libgtk-3-0, libgstreamer-plugins-base1.0-0

# ================================ fpi ======================================
name=${name}-fpi

for pi_cpu in "$@"
do
  flutterpi_tool build --release ${pi_opts} --cpu ${pi_cpu}
  prepackage
  mkdir -p debian/etc/systemd/system/getty@tty1.service.d
  mv build/flutter_assets debian/usr/share/${name}
  cp boatinstrument-fpi debian/usr/share/${name}
  cp boatinstrument-fpi.getty debian/etc/systemd/system/getty@tty1.service.d/override.conf
  package -${pi_cpu} libgl1-mesa-dri, flutter-pi
done
