version: 2.1

orbs:
  win: circleci/windows@2.4.0

workflows:
  build:
    jobs:
      - install-flutter
#      - build

jobs:
  install-flutter:
    executor:
      name: win/default
    working_directory: C:\Users\circleci\project\flutter
    environment:
#      - Path=C:\Users\circleci\flutter\bin;%Path%
      - PATH=c:/Users/circleci/flutter/bin:%PATH%
    steps:
      # - run:
      #     command: Invoke-WebRequest https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_3.24.0-stable.zip -OutFile C:\Users\circleci\project\flutter.zip
      #     no_output_timeout: 30m
      # - run:
      #     command: Expand-Archive -Path C:\Users\circleci\project\flutter.zip -Destination C:\Users\circleci\project\
      - run:
          # command: flutter doctor
          command: echo %PATH%
          shell: bash.exe

  build:
    executor:
      name: win/default
    working_directory: C:\Users\circleci\project\boatinstrument
    environment:
#      - Path=C:\Users\circleci\flutter\bin;%Path%
      - PATH=c:/Users/circleci/flutter/bin:%PATH%
    steps:
      - checkout:
          path: C:\Users\circleci\project
      - run:
          command: New-Item $Profile.CurrentUserAllHosts -Force Add-Content -Path $Profile.CurrentUserAllHosts -Value '$env:PATH = "C:\Users\circleci\flutter\bin;$env:PATH"'
      - run:
          command: flutter build windows
          shell: bash.exe
#      - store_artifacts:
#          path: .\bin\Release\netcoreapp2.1\win10-x64\publish\circleci-demo-windows.exe
