#!/bin/bash

set -e

export PATH="$PATH:/home/build/flutter/bin:/home/build/.pub-cache/bin"

git clone --depth 1 --recursive https://github.com/philseeley/flutter-pi.git

cd flutter-pi
./package
mv packages/* /tmp/artifacts
